---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-stresscheck
  namespace: stress-check
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kube-stresscheck
  namespace: stress-check
  labels:
    app: kube-stresscheck
spec:
  selector:
    matchLabels:
      app: kube-stresscheck
  template:
    metadata:
      labels:
        app: kube-stresscheck
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - restore-test-dnqg5-worker-eastus2-kgp9g
      serviceAccount: kube-stresscheck
      securityContext:
        runAsUser: 0
      containers:
        - name: kube-stresscheck
          image: quay.io/giantswarm/kube-stresscheck:latest
